"""
Prompt template randomization — makes challenges resistant to regex parsers.

Each challenge type has multiple phrasing variants. Templates are selected
randomly, making it impossible to write a reliable parser.
"""

import random

# ── Reply instructions (appended to every prompt) ─────

REPLY_INSTRUCTIONS = [
    "Reply with ONLY the answer, nothing else.",
    "Respond with just the answer.",
    "Give me only the answer.",
    "Your response should contain nothing but the answer.",
    "Write only the final answer.",
    "Output just the answer, no explanation.",
    "Answer with a single value only.",
    "Just the answer please, nothing more.",
]

def reply_inst():
    return random.choice(REPLY_INSTRUCTIONS)


# ── Reverse string templates ─────────────────────────

REVERSE_TEMPLATES = [
    lambda w: f"Reverse the following string: {w}.",
    lambda w: f"Write the characters of {w} in reverse order.",
    lambda w: f"Spell {w} backwards.",
    lambda w: f"If you flip the string {w} end-to-end, what do you get?",
    lambda w: f"Read {w} from right to left and write what you see.",
    lambda w: f"Take the word {w} and reverse every character.",
    lambda w: f"Starting from the last character to the first, rewrite {w}.",
    lambda w: f"What is the result of reversing all characters in {w}?",
    lambda w: f"Reverse this text exactly as written: {w}.",
    lambda w: f"Give {w} backwards, character by character.",
    lambda w: f"Write {w} in reverse (last character first).",
    lambda w: f"Reverse the order of characters in the string {w}.",
    lambda w: f"Mirror {w} so the first character becomes the last.",
    # 3 new
    lambda w: f"Rewrite the string {w} from the end to the beginning.",
    lambda w: f"What does {w} look like when you read it in reverse?",
    lambda w: f"Flip {w} around — last letter first, first letter last.",
    # 5 more
    lambda w: f"Invert the character order of {w}.",
    lambda w: f"Take {w} and write it back-to-front.",
    lambda w: f"How would {w} read if you started from the last character?",
    lambda w: f"Produce the reverse of the string {w}.",
    lambda w: f"If you read {w} from right to left, what string do you get?",
]

# ── Math templates ────────────────────────────────────

MATH_TEMPLATES = {
    "add": [
        lambda a, b: f"What is {a} + {b}?",
        lambda a, b: f"Calculate the sum of {a} and {b}.",
        lambda a, b: f"Add {a} to {b}. What do you get?",
        lambda a, b: f"If you combine {a} and {b}, what is the total?",
        lambda a, b: f"Compute {a} plus {b}.",
        # 8 new
        lambda a, b: f"Find the result of adding {a} and {b} together.",
        lambda a, b: f"Sum up {a} and {b}.",
        lambda a, b: f"How much is {a} added to {b}?",
        lambda a, b: f"{a} + {b} = ?",
        lambda a, b: f"Tell me what {a} plus {b} equals.",
        lambda a, b: f"What do you get if you add {a} and {b}?",
        lambda a, b: f"Determine the value of {a} + {b}.",
        lambda a, b: f"Please compute the sum: {a} + {b}.",
        lambda a, b: f"Work out {a} plus {b}.",
        lambda a, b: f"Figure out the answer to {a} + {b}.",
        lambda a, b: f"Give me the total of {a} and {b}.",
        lambda a, b: f"Evaluate {a} + {b}.",
        lambda a, b: f"If I have {a} and add {b}, what do I get?",
    ],
    "subtract": [
        lambda a, b: f"What is {a} - {b}?",
        lambda a, b: f"Subtract {b} from {a}.",
        lambda a, b: f"If you take {b} away from {a}, what remains?",
        lambda a, b: f"Calculate {a} minus {b}.",
        # 8 new
        lambda a, b: f"Find the difference between {a} and {b}.",
        lambda a, b: f"{a} - {b} = ?",
        lambda a, b: f"How much is {a} minus {b}?",
        lambda a, b: f"Remove {b} from {a}. What is left?",
        lambda a, b: f"Compute the result of {a} minus {b}.",
        lambda a, b: f"What remains when {b} is subtracted from {a}?",
        lambda a, b: f"Determine {a} - {b}.",
        lambda a, b: f"Take {b} from {a} and tell me the result.",
        lambda a, b: f"Work out {a} minus {b}.",
        lambda a, b: f"What do you get subtracting {b} from {a}?",
        lambda a, b: f"Figure out {a} - {b}.",
        lambda a, b: f"Evaluate {a} minus {b}.",
        lambda a, b: f"Give me the result of {a} minus {b}.",
    ],
    "multiply": [
        lambda a, b: f"What is {a} × {b}?",
        lambda a, b: f"Multiply {a} by {b}.",
        lambda a, b: f"Calculate the product of {a} and {b}.",
        lambda a, b: f"What do you get when you multiply {a} times {b}?",
        # 8 new
        lambda a, b: f"{a} × {b} = ?",
        lambda a, b: f"Find the product of {a} and {b}.",
        lambda a, b: f"How much is {a} multiplied by {b}?",
        lambda a, b: f"What is {a} times {b}?",
        lambda a, b: f"Compute {a} * {b}.",
        lambda a, b: f"Tell me what {a} times {b} equals.",
        lambda a, b: f"If you multiply {a} and {b}, what is the result?",
        lambda a, b: f"Determine the value of {a} × {b}.",
        lambda a, b: f"Work out {a} times {b}.",
        lambda a, b: f"Calculate {a} * {b}.",
        lambda a, b: f"Give me the product: {a} × {b}.",
        lambda a, b: f"Evaluate {a} multiplied by {b}.",
        lambda a, b: f"What does {a} × {b} equal?",
    ],
    "add_three": [
        lambda a, b, c: f"What is {a} + {b} + {c}?",
        lambda a, b, c: f"Add together {a}, {b}, and {c}.",
        lambda a, b, c: f"Find the sum of these three numbers: {a}, {b}, {c}.",
        lambda a, b, c: f"Calculate {a} plus {b} plus {c}.",
        # 8 new
        lambda a, b, c: f"Sum {a}, {b}, and {c}.",
        lambda a, b, c: f"{a} + {b} + {c} = ?",
        lambda a, b, c: f"What is the total of {a}, {b}, and {c}?",
        lambda a, b, c: f"Combine {a}, {b}, and {c}. What do you get?",
        lambda a, b, c: f"How much do {a}, {b}, and {c} add up to?",
        lambda a, b, c: f"Compute the sum of {a}, {b}, and {c}.",
        lambda a, b, c: f"If you add {a}, {b}, and {c}, what is the result?",
        lambda a, b, c: f"Tell me the sum: {a} + {b} + {c}.",
        lambda a, b, c: f"Work out {a} + {b} + {c}.",
        lambda a, b, c: f"Evaluate the expression {a} + {b} + {c}.",
        lambda a, b, c: f"Give me the total when you add {a}, {b}, and {c}.",
        lambda a, b, c: f"Figure out: {a} + {b} + {c}.",
        lambda a, b, c: f"What does {a} + {b} + {c} equal?",
    ],
    "subtract_chain": [
        lambda a, b, c: f"What is {a} - {b} - {c}?",
        lambda a, b, c: f"Start with {a}, subtract {b}, then subtract {c}.",
        lambda a, b, c: f"Take {a}, remove {b}, then remove another {c}. What's left?",
        # 8 new
        lambda a, b, c: f"{a} - {b} - {c} = ?",
        lambda a, b, c: f"Calculate {a} minus {b} minus {c}.",
        lambda a, b, c: f"From {a}, subtract first {b} then {c}.",
        lambda a, b, c: f"Begin with {a}. Deduct {b} and then {c}. What remains?",
        lambda a, b, c: f"Compute {a} - {b} - {c}.",
        lambda a, b, c: f"What do you get when you subtract {b} and {c} from {a}?",
        lambda a, b, c: f"Find the result: {a} minus {b} minus {c}.",
        lambda a, b, c: f"If you take away {b} and {c} from {a}, what's left?",
        lambda a, b, c: f"Work out {a} - {b} - {c}.",
        lambda a, b, c: f"Evaluate {a} minus {b} minus {c}.",
        lambda a, b, c: f"Figure out: {a} - {b} - {c}.",
        lambda a, b, c: f"What does {a} - {b} - {c} equal?",
        lambda a, b, c: f"Give me the result of subtracting {b} and then {c} from {a}.",
    ],
    "mixed": [
        lambda a, b, c: f"What is {a} + {b} - {c}?",
        lambda a, b, c: f"Calculate {a} plus {b} minus {c}.",
        lambda a, b, c: f"Add {a} and {b}, then subtract {c}. What do you get?",
        lambda a, b, c: f"Compute the result of {a} + {b} - {c}.",
        lambda a, b, c: f"{a} + {b} - {c} = ?",
        lambda a, b, c: f"Start with {a}, add {b}, and subtract {c}.",
        lambda a, b, c: f"Find the value of {a} plus {b} minus {c}.",
        lambda a, b, c: f"What remains if you combine {a} and {b}, then take away {c}?",
        lambda a, b, c: f"Work out {a} + {b} - {c}.",
        lambda a, b, c: f"Figure out: {a} plus {b} minus {c}.",
        lambda a, b, c: f"Evaluate {a} + {b} - {c}.",
        lambda a, b, c: f"What does {a} + {b} - {c} equal?",
        lambda a, b, c: f"Give me the answer to {a} plus {b}, then subtract {c}.",
    ],
    "modulo": [
        lambda a, b: f"What is {a} mod {b}? (the remainder when {a} is divided by {b})",
        lambda a, b: f"Calculate the remainder of {a} divided by {b}.",
        lambda a, b: f"What is the remainder when {a} is divided by {b}?",
        lambda a, b: f"Compute {a} % {b} (modulo operation).",
        lambda a, b: f"Find the remainder: {a} ÷ {b}.",
        lambda a, b: f"If you divide {a} by {b}, what is the remainder?",
        lambda a, b: f"Determine {a} modulo {b}.",
        lambda a, b: f"{a} mod {b} = ?",
        lambda a, b: f"Work out the remainder of {a} ÷ {b}.",
        lambda a, b: f"What is left over when you divide {a} by {b}?",
        lambda a, b: f"Figure out {a} modulo {b}.",
        lambda a, b: f"Evaluate {a} % {b}.",
        lambda a, b: f"Give me the modulo result: {a} mod {b}.",
    ],
}

# ── Letter position templates ─────────────────────────

LETTER_POS_TEMPLATES = [
    lambda w: f'If A=1, B=2, C=3, ... Z=26, what is the sum of the letter values in "{w}"?',
    lambda w: f'Assign each letter a number (A=1, B=2, through Z=26). Add up the values of all letters in "{w}".',
    lambda w: f'Using the mapping A→1, B→2, C→3, ..., Z→26, calculate the total value of the letters in "{w}".',
    lambda w: f'Each letter has a position in the alphabet (A=1, Z=26). What is the sum of positions for the letters in "{w}"?',
    # 8 new
    lambda w: f'Given A=1, B=2, ..., Z=26, compute the sum of all letter values in "{w}".',
    lambda w: f'Map each letter to its alphabet position (A=1 through Z=26) and find the total for "{w}".',
    lambda w: f'What is the alphabet position sum for the letters in "{w}"? (A=1, B=2, ..., Z=26)',
    lambda w: f'For the string "{w}", convert each letter to its position number (A=1, B=2, ...) and add them all up.',
    lambda w: f'Calculate the total alphabetical value of "{w}" where A=1, B=2, C=3, and so on.',
    lambda w: f'Sum the positions of all letters in "{w}" using the scheme A=1, B=2, ..., Z=26.',
    lambda w: f'In "{w}", each letter has a value equal to its position in the alphabet. What is the total?',
    lambda w: f'Add together the alphabetic positions of every letter in "{w}" (A=1, Z=26).',
    lambda w: f'What is the combined alphabetical value of all letters in "{w}"? (A=1, B=2, ..., Z=26)',
    lambda w: f'Compute the alphabet-position total for "{w}" (A=1 through Z=26).',
    lambda w: f'If each letter equals its position (A=1, B=2, ..., Z=26), what is the total for "{w}"?',
    lambda w: f'Determine the positional sum of "{w}" where each letter is worth its place in the alphabet.',
    lambda w: f'For "{w}", assign A=1, B=2, ..., Z=26 and give the total.',
]

# ── ROT13 templates ───────────────────────────────────

ROT13_TEMPLATES = [
    lambda enc: f"Decode this ROT13-encoded string (each letter shifts 13 places back in the alphabet): {enc}",
    lambda enc: f"Apply ROT13 decoding to the text: {enc}",
    lambda enc: f"The following text was encoded with ROT13. Decode it: {enc}",
    lambda enc: f"Shift each letter in {enc} by 13 positions in the alphabet to decode it.",
    # 8 new
    lambda enc: f"This string has been ROT13-encoded: {enc}. What is the decoded version?",
    lambda enc: f"Reverse the ROT13 encoding of: {enc}",
    lambda enc: f"Decode {enc} using the ROT13 cipher (rotate each letter by 13).",
    lambda enc: f"The text {enc} was scrambled with ROT13. Unscramble it.",
    lambda enc: f"Apply the ROT13 algorithm to decipher this: {enc}",
    lambda enc: f"What does {enc} say when you undo the ROT13 encoding?",
    lambda enc: f"Each letter in {enc} was shifted 13 places forward. Shift them back to decode.",
    lambda enc: f"ROT13 decrypt this string: {enc}",
    lambda enc: f"Perform ROT13 decoding on: {enc}",
    lambda enc: f"The string {enc} is ROT13-encoded. Decode it back to the original.",
    lambda enc: f"Un-ROT13 this: {enc}",
    lambda enc: f"Rotate every letter in {enc} by 13 positions to decode it.",
    lambda enc: f"What is the plaintext of this ROT13 cipher: {enc}?",
]

# ── Pattern templates ─────────────────────────────────

PATTERN_TEMPLATES = [
    lambda seq: f"What comes next in this sequence: {seq}, ?",
    lambda seq: f"Find the next number: {seq}, ?",
    lambda seq: f"Continue this pattern: {seq}, ?",
    lambda seq: f"What number follows this sequence: {seq}, ?",
    lambda seq: f"Identify the next value in the series: {seq}, ?",
    # 8 new
    lambda seq: f"Determine the next number in the pattern: {seq}, ?",
    lambda seq: f"What is the next term in this sequence: {seq}, ?",
    lambda seq: f"Extend this series by one: {seq}, ?",
    lambda seq: f"The sequence goes: {seq}. What comes next?",
    lambda seq: f"Look at this pattern: {seq}. What is the next value?",
    lambda seq: f"Given the series {seq}, find the number that follows.",
    lambda seq: f"Here is a number sequence: {seq}. What should the next number be?",
    lambda seq: f"Predict the next element: {seq}, ?",
    lambda seq: f"Analyze the pattern: {seq}. What number is next?",
    lambda seq: f"Work out the rule and give the next number: {seq}, ?",
    lambda seq: f"This series follows a rule: {seq}. What is the next entry?",
    lambda seq: f"Complete the sequence with one more number: {seq}, ?",
    lambda seq: f"Figure out what comes after {seq}.",
]

# ── Extract templates ─────────────────────────────────

EXTRACT_TEMPLATES = {
    2: [
        lambda mixed: f"Extract every 2nd letter from this string, starting from the 1st character: {mixed}",
        lambda mixed: f"Take every other character from {mixed}, beginning with the first.",
        lambda mixed: f"From the string {mixed}, pick characters at positions 1, 3, 5, 7... What do you get?",
        # 8 new
        lambda mixed: f"Read only the odd-positioned characters in {mixed} (1st, 3rd, 5th...).",
        lambda mixed: f"From {mixed}, extract characters at positions 1, 3, 5, 7, and so on.",
        lambda mixed: f"Skip every other letter in {mixed}, starting by keeping the first character.",
        lambda mixed: f"Take the 1st, 3rd, 5th, 7th... characters from {mixed}.",
        lambda mixed: f"What do you get when you select every second character from {mixed}, starting with the first?",
        lambda mixed: f"Pick out alternating characters from {mixed}, beginning with the first one.",
        lambda mixed: f"In {mixed}, keep only the characters at odd positions (1, 3, 5, ...).",
        lambda mixed: f"Extract characters at indices 0, 2, 4, 6... from the string {mixed}.",
        lambda mixed: f"Read every other letter from {mixed}, starting with the first.",
        lambda mixed: f"Pull out characters 1, 3, 5, 7... from the string {mixed}.",
        lambda mixed: f"From {mixed}, keep only positions 1, 3, 5, 7... (1-indexed).",
        lambda mixed: f"Take alternate characters from {mixed}, beginning at the start.",
        lambda mixed: f"Select the characters at positions 0, 2, 4... in {mixed}.",
    ],
    3: [
        lambda mixed: f"Extract every 3rd letter from this string, starting from the 1st character: {mixed}",
        lambda mixed: f"From {mixed}, take the 1st, 4th, 7th, 10th... characters.",
        lambda mixed: f"Pick every third character from {mixed}, starting at position 1.",
        # 8 new
        lambda mixed: f"From the string {mixed}, select the character at position 1, then every 3rd character after that.",
        lambda mixed: f"In {mixed}, extract the 1st character, then skip 2 and take the next, repeating this pattern.",
        lambda mixed: f"Read characters at positions 1, 4, 7, 10... from {mixed}.",
        lambda mixed: f"Take every third letter from {mixed}, beginning with the very first one.",
        lambda mixed: f"What word do you get by selecting the 1st, 4th, 7th, 10th... letters from {mixed}?",
        lambda mixed: f"Skip two characters, keep one — starting from position 1 in {mixed}.",
        lambda mixed: f"From {mixed}, pick out characters at indices 0, 3, 6, 9...",
        lambda mixed: f"Extract every 3rd character from {mixed} starting at the beginning.",
        lambda mixed: f"Read the 1st character of {mixed}, then every 3rd one after that.",
        lambda mixed: f"Pull out characters at positions 1, 4, 7, 10... from {mixed}.",
        lambda mixed: f"Select every third character from {mixed}, beginning at position 1.",
        lambda mixed: f"From {mixed}, keep the 1st, then skip two, keep one, and repeat.",
        lambda mixed: f"Collect characters at indices 0, 3, 6, 9... from the string {mixed}.",
    ],
}

# ── Word math templates ───────────────────────────────

WORD_MATH_TEMPLATES = {
    "digit_to_word": [
        lambda a, b: f'What is {a} + {b}? Write the answer as a word (e.g., "twelve"), not a number.',
        lambda a, b: f"Add {a} and {b}. Spell out the answer as an English word.",
        lambda a, b: f"Calculate {a} + {b} and write the result as a word, not a digit.",
        # 8 new
        lambda a, b: f"What is the sum of {a} and {b}? Respond using the English word for the number.",
        lambda a, b: f"Compute {a} plus {b} and express the answer as a word.",
        lambda a, b: f"{a} + {b} = ? Write the answer as a word (like \"seven\"), not a numeral.",
        lambda a, b: f"Add {a} to {b}. Give the answer spelled out in English.",
        lambda a, b: f"Find {a} + {b} and write the result as an English number word.",
        lambda a, b: f"What word represents the sum of {a} and {b}?",
        lambda a, b: f"Sum {a} and {b}. Spell the answer as a word instead of a digit.",
        lambda a, b: f"Tell me {a} plus {b} using the English word for the number.",
        lambda a, b: f"Express the sum of {a} and {b} as an English word.",
        lambda a, b: f"Write the result of {a} + {b} as a word, not digits.",
        lambda a, b: f"Calculate {a} + {b}. Reply with the English word for that number.",
        lambda a, b: f"Figure out {a} + {b} and give the answer as a word.",
        lambda a, b: f"What is {a} + {b}? Use a word, not a numeral.",
    ],
    "char_count": [
        lambda w: f'How many characters are in the string "{w}"?',
        lambda w: f'Count the total number of letters in "{w}".',
        lambda w: f'What is the length of the string "{w}"?',
        # 8 new
        lambda w: f'How many letters does "{w}" contain?',
        lambda w: f'Determine the character count of "{w}".',
        lambda w: f'What is the total number of characters in "{w}"?',
        lambda w: f'Count all the characters in the string "{w}".',
        lambda w: f'How long is the string "{w}"? Give the number of characters.',
        lambda w: f'Tell me how many letters are in "{w}".',
        lambda w: f'Find the length of "{w}" in characters.',
        lambda w: f'"{w}" — how many characters is that?',
        lambda w: f'Give me the character count for the string "{w}".',
        lambda w: f'How many individual characters make up "{w}"?',
        lambda w: f'Calculate the length of "{w}" in characters.',
        lambda w: f'What is the size of "{w}" in terms of character count?',
        lambda w: f'String "{w}" — count every character.',
    ],
    "vowel_count": [
        lambda w: f'How many vowels (A, E, I, O, U) are in "{w}"?',
        lambda w: f'Count the vowels in the string "{w}".',
        lambda w: f'In the text "{w}", how many letters are vowels (A, E, I, O, U)?',
        # 8 new
        lambda w: f'How many of the letters in "{w}" are vowels?',
        lambda w: f'Find the number of vowels (A, E, I, O, U) in "{w}".',
        lambda w: f'Count how many times A, E, I, O, or U appears in "{w}".',
        lambda w: f'What is the vowel count for the string "{w}"?',
        lambda w: f'In "{w}", tally up all the vowels (A, E, I, O, U).',
        lambda w: f'How many vowel letters does "{w}" contain?',
        lambda w: f'Tell me the number of vowels in "{w}".',
        lambda w: f'Scan "{w}" and count every A, E, I, O, and U.',
        lambda w: f'Count each vowel character in "{w}" (A, E, I, O, U).',
        lambda w: f'What is the total number of A, E, I, O, and U in "{w}"?',
        lambda w: f'Determine the vowel total for "{w}".',
        lambda w: f'Go through "{w}" and count all vowels.',
        lambda w: f'In the string "{w}", find the total vowel count.',
    ],
    "digit_sum": [
        lambda n: f"What is the sum of the digits of {n}?",
        lambda n: f"Add up each individual digit in the number {n}.",
        lambda n: f"Take the number {n} and sum its digits together.",
        # 8 new
        lambda n: f"Calculate the digit sum of {n}.",
        lambda n: f"What do you get when you add all the digits of {n}?",
        lambda n: f"Sum every digit in the number {n}.",
        lambda n: f"Find the total when you add each digit of {n} individually.",
        lambda n: f"Break {n} into its individual digits and add them up.",
        lambda n: f"What is the result of summing all digits in {n}?",
        lambda n: f"Compute the digit sum: take {n} and add up each digit.",
        lambda n: f"For the number {n}, find the sum of its digits.",
        lambda n: f"Total up each digit in {n}.",
        lambda n: f"Find the digital root sum of {n} (add all digits).",
        lambda n: f"What total do you get from adding the digits of {n}?",
        lambda n: f"Decompose {n} into individual digits and sum them.",
        lambda n: f"Digit by digit, add up {n}.",
    ],
}

# ── Caesar templates ──────────────────────────────────

CAESAR_TEMPLATES = [
    lambda enc, s: f"Decode this Caesar cipher (each letter is shifted {s} positions forward in the alphabet): {enc}\nShift each letter {s} positions BACKWARD to decode.",
    lambda enc, s: f"The text {enc} was encrypted with a Caesar shift of {s}. Decrypt it by shifting each letter back by {s}.",
    lambda enc, s: f"Apply a reverse Caesar shift of {s} to decode: {enc}",
    lambda enc, s: f"This message was encoded by shifting each letter forward by {s} in the alphabet: {enc}. What is the original text?",
    # 8 new
    lambda enc, s: f"Decrypt the Caesar cipher {enc} by shifting each letter {s} positions backward.",
    lambda enc, s: f"Each letter in {enc} was shifted forward by {s}. Reverse the shift to decode.",
    lambda enc, s: f"The cipher text is {enc}, encoded with a shift of {s}. What was the original message?",
    lambda enc, s: f"Undo a Caesar shift of {s} on this text: {enc}",
    lambda enc, s: f"Caesar decode {enc} with shift={s}. Move each letter {s} places back in the alphabet.",
    lambda enc, s: f"Given the Caesar-encrypted text {enc} (shift {s}), determine the plaintext.",
    lambda enc, s: f"Decipher this by reversing a {s}-position Caesar shift: {enc}",
    lambda enc, s: f"Shift every letter in {enc} backward by {s} positions to reveal the original word.",
    lambda enc, s: f"The text {enc} uses a Caesar cipher with shift {s}. Decode it.",
    lambda enc, s: f"Decrypt: {enc} (Caesar shift = {s}, shift backward to decode).",
    lambda enc, s: f"Move each letter in {enc} back {s} places in the alphabet to decode.",
    lambda enc, s: f"What was the original text before a Caesar shift of {s} was applied to get {enc}?",
    lambda enc, s: f"Reverse a {s}-step Caesar cipher on {enc}. What do you get?",
]

# ── Sorting templates ─────────────────────────────────

SORTING_TEMPLATES = {
    "sort_letters": [
        lambda w: f"Sort these letters in alphabetical order: {w}",
        lambda w: f"Arrange the letters {w} from A to Z.",
        lambda w: f"Put these letters in alphabetical sequence: {w}",
        # 8 new
        lambda w: f"Alphabetize the letters: {w}",
        lambda w: f"Reorder {w} so the letters go from A to Z.",
        lambda w: f"What does {w} look like when the letters are sorted alphabetically?",
        lambda w: f"Arrange the characters {w} in alphabetical order.",
        lambda w: f"Sort {w} from first to last in the alphabet.",
        lambda w: f"Order these letters alphabetically: {w}",
        lambda w: f"Take the letters {w} and sort them A→Z.",
        lambda w: f"Rearrange {w} into alphabetical order.",
        lambda w: f"Put the characters of {w} in A–Z order.",
        lambda w: f"List the letters of {w} sorted from A to Z.",
        lambda w: f"Organize {w} alphabetically.",
        lambda w: f"Give me {w} with its letters in alphabetical sequence.",
        lambda w: f"How do the letters of {w} look when sorted?",
    ],
    "sort_numbers": [
        lambda nums: f"Sort these numbers from smallest to largest: {nums}",
        lambda nums: f"Arrange in ascending order: {nums}",
        lambda nums: f"Put these numbers in order from lowest to highest: {nums}",
        # 8 new
        lambda nums: f"Order these numbers from least to greatest: {nums}",
        lambda nums: f"Sort in ascending order: {nums}",
        lambda nums: f"Rearrange these numbers from smallest to biggest: {nums}",
        lambda nums: f"What is the ascending order of: {nums}?",
        lambda nums: f"List these numbers sorted from low to high: {nums}",
        lambda nums: f"Arrange {nums} in increasing order.",
        lambda nums: f"Put {nums} in numerical order (smallest first).",
        lambda nums: f"Sort from minimum to maximum: {nums}",
        lambda nums: f"Place these numbers in order, smallest first: {nums}",
        lambda nums: f"What is the sorted (ascending) form of: {nums}?",
        lambda nums: f"Organize {nums} from lowest to highest.",
        lambda nums: f"Give me {nums} arranged in ascending order.",
        lambda nums: f"Rank these numbers from smallest to largest: {nums}",
    ],
    "sort_reverse": [
        lambda w: f"Sort these letters in REVERSE alphabetical order (Z first, A last): {w}",
        lambda w: f"Arrange the letters {w} from Z to A.",
        lambda w: f"Put these letters in reverse alphabetical order: {w}",
        # 8 new
        lambda w: f"Sort {w} in descending alphabetical order.",
        lambda w: f"Order the letters {w} from Z to A.",
        lambda w: f"Rearrange {w} in reverse alphabetical order (Z first).",
        lambda w: f"What does {w} look like sorted from Z to A?",
        lambda w: f"Take the letters {w} and sort them Z→A.",
        lambda w: f"Arrange {w} in reverse (Z before A).",
        lambda w: f"Sort these letters backwards through the alphabet: {w}",
        lambda w: f"Put {w} in descending alphabetical order.",
        lambda w: f"Give me {w} sorted from Z to A.",
        lambda w: f"Reverse-alphabetize {w}.",
        lambda w: f"Organize {w} in Z-to-A order.",
        lambda w: f"List the letters of {w} sorted in descending order.",
        lambda w: f"How does {w} look when sorted in reverse alphabetical order?",
    ],
    "sort_words": [
        lambda words: f"Sort these words alphabetically: {words}",
        lambda words: f"Arrange these words in alphabetical order: {words}",
        lambda words: f"Put these words in order from A to Z: {words}",
        lambda words: f"Alphabetize the following words: {words}",
        lambda words: f"What is the alphabetical order of: {words}?",
        lambda words: f"Reorder these words alphabetically: {words}",
        lambda words: f"List these words sorted A→Z: {words}",
        lambda words: f"Sort from first to last alphabetically: {words}",
        lambda words: f"Organize these words from A to Z: {words}",
        lambda words: f"Give me these words in alphabetical sequence: {words}",
        lambda words: f"How do these words sort alphabetically: {words}?",
        lambda words: f"Place these in alphabetical order: {words}",
        lambda words: f"Arrange A–Z: {words}",
    ],
    "sort_numbers_reverse": [
        lambda nums: f"Sort these numbers from largest to smallest: {nums}",
        lambda nums: f"Arrange in descending order: {nums}",
        lambda nums: f"Put these numbers in order from highest to lowest: {nums}",
        lambda nums: f"Order these numbers from greatest to least: {nums}",
        lambda nums: f"Sort in descending order: {nums}",
        lambda nums: f"Rearrange these numbers from biggest to smallest: {nums}",
        lambda nums: f"List these numbers from high to low: {nums}",
        lambda nums: f"Sort from maximum to minimum: {nums}",
        lambda nums: f"Place these numbers in order, largest first: {nums}",
        lambda nums: f"What is the sorted (descending) form of: {nums}?",
        lambda nums: f"Organize {nums} from highest to lowest.",
        lambda nums: f"Give me {nums} arranged in descending order.",
        lambda nums: f"Rank these from biggest to smallest: {nums}",
    ],
}

# ── Counting templates ────────────────────────────────

COUNTING_TEMPLATES = {
    "count_letter": [
        lambda t, text: f'How many times does the letter "{t}" appear in "{text}"?',
        lambda t, text: f'Count the occurrences of "{t}" in the string "{text}".',
        lambda t, text: f'In "{text}", how many "{t}" characters are there?',
        # 8 new
        lambda t, text: f'How often does "{t}" show up in "{text}"?',
        lambda t, text: f'Find the number of times "{t}" appears in "{text}".',
        lambda t, text: f'Scan the string "{text}" and count every "{t}".',
        lambda t, text: f'What is the frequency of the letter "{t}" in "{text}"?',
        lambda t, text: f'Count all instances of "{t}" within "{text}".',
        lambda t, text: f'How many "{t}" letters can you find in "{text}"?',
        lambda t, text: f'Tell me the count of "{t}" in the string "{text}".',
        lambda t, text: f'In the string "{text}", tally up every occurrence of "{t}".',
        lambda t, text: f'Go through "{text}" and count each "{t}".',
        lambda t, text: f'For the string "{text}", how many times is "{t}" present?',
        lambda t, text: f'Determine the number of "{t}" occurrences in "{text}".',
        lambda t, text: f'Count every "{t}" in "{text}" and give the total.',
        lambda t, text: f'What is the total number of "{t}" characters in "{text}"?',
    ],
    "count_consonants": [
        lambda w: f'How many consonants (non-vowel letters) are in "{w}"?',
        lambda w: f'Count all consonants in the string "{w}".',
        lambda w: f'In "{w}", how many letters are NOT vowels?',
        # 8 new
        lambda w: f'What is the consonant count for "{w}"?',
        lambda w: f'How many non-vowel letters does "{w}" contain?',
        lambda w: f'Find the number of consonants in "{w}".',
        lambda w: f'Tally the consonants in the string "{w}".',
        lambda w: f'Count the letters in "{w}" that are not A, E, I, O, or U.',
        lambda w: f'In "{w}", how many consonant characters are there?',
        lambda w: f'Determine the number of consonants in "{w}".',
        lambda w: f'How many letters in "{w}" are consonants (not vowels)?',
        lambda w: f'Count every non-vowel character in "{w}".',
        lambda w: f'Go through "{w}" and count only the consonants.',
        lambda w: f'For "{w}", give the number of letters that are not vowels.',
        lambda w: f'Tell me the total consonants in the string "{w}".',
        lambda w: f'In "{w}", how many characters are consonants?',
    ],
    "count_digits": [
        lambda t, d: f'How many times does the digit "{t}" appear in "{d}"?',
        lambda t, d: f'Count how often "{t}" occurs in the number string "{d}".',
        # 8 new
        lambda t, d: f'In the string "{d}", how many "{t}" digits are there?',
        lambda t, d: f'Find the count of digit "{t}" in "{d}".',
        lambda t, d: f'Scan "{d}" and tell me how many times "{t}" appears.',
        lambda t, d: f'What is the frequency of "{t}" in the number string "{d}"?',
        lambda t, d: f'Count all occurrences of the digit "{t}" in "{d}".',
        lambda t, d: f'How often does the digit "{t}" show up in "{d}"?',
        lambda t, d: f'In "{d}", tally every "{t}".',
        lambda t, d: f'Determine how many "{t}" digits are in "{d}".',
        lambda t, d: f'Go through "{d}" and count every "{t}" digit.',
        lambda t, d: f'For the number string "{d}", tell me the count of "{t}".',
        lambda t, d: f'Count each "{t}" in the string "{d}".',
        lambda t, d: f'What is the total number of "{t}" digits within "{d}"?',
        lambda t, d: f'In "{d}", how many times can you find the digit "{t}"?',
    ],
    "count_upper": [
        lambda text: f'How many UPPERCASE letters are in "{text}"?',
        lambda text: f'Count the capital letters in "{text}".',
        lambda text: f'In the mixed-case string "{text}", how many characters are uppercase?',
        # 8 new
        lambda text: f'Find the number of uppercase characters in "{text}".',
        lambda text: f'How many capital letters does "{text}" contain?',
        lambda text: f'Tally all the uppercase letters in "{text}".',
        lambda text: f'What is the uppercase letter count for "{text}"?',
        lambda text: f'In "{text}", count every character that is a capital letter.',
        lambda text: f'How many of the letters in "{text}" are uppercase?',
        lambda text: f'Scan "{text}" and count the uppercase letters.',
        lambda text: f'Tell me the number of capital letters in "{text}".',
        lambda text: f'Count every uppercase character in the string "{text}".',
        lambda text: f'Go through "{text}" and count the capital letters.',
        lambda text: f'For "{text}", give the number of uppercase characters.',
        lambda text: f'How many of the characters in "{text}" are uppercase letters?',
        lambda text: f'Determine the uppercase character count in "{text}".',
    ],
}

# ── Transform templates ───────────────────────────────

TRANSFORM_TEMPLATES = {
    "remove_vowels": [
        lambda w: f'Remove all vowels (A, E, I, O, U) from "{w}".',
        lambda w: f'Delete every vowel from the string "{w}". What remains?',
        lambda w: f'Strip out A, E, I, O, and U from "{w}".',
        # 8 new
        lambda w: f'Take "{w}" and remove all vowels.',
        lambda w: f'What do you get when you remove A, E, I, O, U from "{w}"?',
        lambda w: f'From "{w}", delete every A, E, I, O, and U.',
        lambda w: f'Eliminate all vowels from the string "{w}".',
        lambda w: f'Remove each vowel (A, E, I, O, U) from "{w}" and write what is left.',
        lambda w: f'Drop all the vowels from "{w}".',
        lambda w: f'What remains of "{w}" after removing all vowels?',
        lambda w: f'Strip every vowel from "{w}" and give the result.',
        lambda w: f'Delete A, E, I, O, U from "{w}". What is left?',
        lambda w: f'Go through "{w}" and remove every vowel character.',
        lambda w: f'Remove the vowels from the string "{w}" and write the remainder.',
        lambda w: f'Clear out all A, E, I, O, U characters from "{w}".',
        lambda w: f'After deleting all vowels from "{w}", what do you have?',
    ],
    "remove_consonants": [
        lambda w: f'Remove all consonants from "{w}" and keep only the vowels (A, E, I, O, U).',
        lambda w: f'Extract only the vowels from "{w}".',
        lambda w: f'From the string "{w}", delete every consonant and keep only vowels.',
        # 8 new
        lambda w: f'Keep only the vowels in "{w}" and discard all consonants.',
        lambda w: f'What vowels appear in "{w}"? List them in order.',
        lambda w: f'Strip out all consonants from "{w}", keeping only A, E, I, O, U.',
        lambda w: f'From "{w}", remove every letter that is not a vowel.',
        lambda w: f'Extract the vowels from "{w}" in the order they appear.',
        lambda w: f'Delete all non-vowel letters from "{w}".',
        lambda w: f'After removing consonants from "{w}", what letters remain?',
        lambda w: f'Filter "{w}" to keep only vowels (A, E, I, O, U).',
        lambda w: f'Eliminate every consonant from "{w}" and give the remaining vowels.',
        lambda w: f'What are just the vowels in "{w}", in order?',
        lambda w: f'Remove all non-vowel letters from the string "{w}".',
        lambda w: f'Go through "{w}" and keep only A, E, I, O, U.',
        lambda w: f'Collect all the vowels from "{w}" in their original order.',
    ],
    "first_letters": [
        lambda s: f'What do the first letters of each word spell: "{s}"?',
        lambda s: f'Take the initial letter of every word in "{s}" and combine them.',
        lambda s: f'Form an acronym from: "{s}".',
        # 8 new
        lambda s: f'Create an acronym by taking the first letter of each word in "{s}".',
        lambda s: f'What word do the initial letters of "{s}" spell?',
        lambda s: f'Extract the first letter of each word in "{s}" and join them.',
        lambda s: f'Take the opening letter from every word in "{s}" and combine them.',
        lambda s: f'If you take the first letter of each word in "{s}", what do you get?',
        lambda s: f'Form a word from the initial letters of: "{s}".',
        lambda s: f'Read the first character of each word in "{s}" and string them together.',
        lambda s: f'What is the acronym for "{s}"?',
        lambda s: f'Make an acronym from the words in "{s}".',
        lambda s: f'Join the first letter of each word in "{s}" into one string.',
        lambda s: f'What string do you get by taking each initial letter from "{s}"?',
        lambda s: f'Build a string from the first letters of every word in "{s}".',
        lambda s: f'Collect the starting letter of each word in "{s}" and combine them.',
    ],
    "last_letters": [
        lambda s: f'What do the LAST letters of each word spell: "{s}"?',
        lambda s: f'Take the final letter of each word in "{s}" and combine them.',
        lambda s: f'Extract the ending letter from every word in "{s}" and join them.',
        # 8 new
        lambda s: f'What word do the last letters of each word in "{s}" spell?',
        lambda s: f'Read the final character of each word in "{s}" and combine them.',
        lambda s: f'If you take the last letter of every word in "{s}", what do you get?',
        lambda s: f'From "{s}", pick the ending letter of each word and join them together.',
        lambda s: f'Collect the last letter of every word in "{s}" and form a string.',
        lambda s: f'Extract the terminal letter from each word in "{s}" and concatenate them.',
        lambda s: f'What do you get when you take the final letter of each word in "{s}"?',
        lambda s: f'Take the closing letter of every word in "{s}" and put them together.',
        lambda s: f'Build a string from the last letters of each word in "{s}".',
        lambda s: f'What string do the ending letters of "{s}" form?',
        lambda s: f'Collect the final character of every word in "{s}" and combine them.',
        lambda s: f'Join the last letter of each word in "{s}" into one string.',
        lambda s: f'Read the terminal letter from each word in "{s}" and string them together.',
    ],
    "swap_case": [
        lambda w: f'Swap the case of every letter in "{w}" (uppercase becomes lowercase, lowercase becomes uppercase).',
        lambda w: f'Invert the case of each character in "{w}".',
        lambda w: f'Toggle uppercase and lowercase for every letter in "{w}".',
        lambda w: f'Change all uppercase letters to lowercase and vice versa in "{w}".',
        lambda w: f'What does "{w}" look like with swapped case?',
        lambda w: f'Flip the case of each letter in "{w}".',
        lambda w: f'For "{w}", convert uppercase to lowercase and lowercase to uppercase.',
        lambda w: f'Apply a case swap to every character in "{w}".',
        lambda w: f'Convert every uppercase letter in "{w}" to lowercase and vice versa.',
        lambda w: f'Reverse the case of each character in "{w}".',
        lambda w: f'For each letter in "{w}", switch uppercase to lowercase and lowercase to uppercase.',
        lambda w: f'If you swap the case of every letter in "{w}", what do you get?',
        lambda w: f'Perform a case inversion on the string "{w}".',
    ],
}

# ── Binary templates ──────────────────────────────────

BINARY_TEMPLATES = {
    "binary_to_decimal": [
        lambda b: f"Convert binary {b} to decimal.",
        lambda b: f"What is the decimal value of the binary number {b}?",
        lambda b: f"Express {b} (binary) as a base-10 number.",
        # 8 new
        lambda b: f"Translate the binary number {b} into decimal.",
        lambda b: f"What decimal number does the binary {b} represent?",
        lambda b: f"Convert {b} from binary to base 10.",
        lambda b: f"Binary {b} equals what in decimal?",
        lambda b: f"Find the decimal equivalent of binary {b}.",
        lambda b: f"If {b} is a binary number, what is it in decimal?",
        lambda b: f"Decode the binary number {b} into its decimal form.",
        lambda b: f"What base-10 number is represented by {b} in binary?",
        lambda b: f"Turn the binary number {b} into a decimal number.",
        lambda b: f"Give me the base-10 value of binary {b}.",
        lambda b: f"Calculate the decimal representation of {b} (binary).",
        lambda b: f"How much is binary {b} in base 10?",
        lambda b: f"Interpret {b} as a binary number and convert to decimal.",
    ],
    "decimal_to_binary": [
        lambda n: f"Convert the decimal number {n} to binary.",
        lambda n: f"What is {n} in binary?",
        lambda n: f"Write {n} as a binary number (no 0b prefix).",
        # 8 new
        lambda n: f"Express {n} in binary form.",
        lambda n: f"Translate {n} from decimal to binary.",
        lambda n: f"What does the number {n} look like in binary?",
        lambda n: f"Convert {n} to base 2.",
        lambda n: f"Write the binary representation of {n}.",
        lambda n: f"Find the binary equivalent of the decimal number {n}.",
        lambda n: f"If you convert {n} to binary, what do you get?",
        lambda n: f"Represent {n} as a binary number.",
        lambda n: f"Turn {n} into binary.",
        lambda n: f"Give me {n} in base-2 notation.",
        lambda n: f"How do you write {n} in binary form?",
        lambda n: f"Determine the binary form of {n}.",
        lambda n: f"Show {n} as a binary number.",
    ],
    "digit_sum": [
        lambda n: f"What is the sum of all digits in {n}?",
        lambda n: f"Add each digit of {n} together.",
        lambda n: f"Calculate the digit sum of {n}.",
        # 8 new
        lambda n: f"Sum the individual digits of {n}.",
        lambda n: f"Break {n} into its digits and find their total.",
        lambda n: f"What do you get when you add up every digit in {n}?",
        lambda n: f"Compute the sum of each digit in the number {n}.",
        lambda n: f"Find the digit sum of {n}.",
        lambda n: f"For the number {n}, add its digits together.",
        lambda n: f"What is the total of all individual digits in {n}?",
        lambda n: f"Add together each digit that makes up {n}.",
        lambda n: f"Total up the individual digits of {n}.",
        lambda n: f"What is the sum when you add each digit of {n}?",
        lambda n: f"Split {n} into digits and find their sum.",
        lambda n: f"Compute the sum of all single digits in {n}.",
        lambda n: f"Add every digit in the number {n} together.",
    ],
    "hex_to_decimal": [
        lambda h: f"Convert hexadecimal {h} to decimal.",
        lambda h: f"What is the decimal value of hex {h}?",
        lambda h: f"Express {h} (hexadecimal) as a base-10 number.",
        lambda h: f"Translate hex {h} into decimal.",
        lambda h: f"What decimal number does the hexadecimal value {h} represent?",
        lambda h: f"Convert {h} from hex to decimal.",
        lambda h: f"Find the base-10 equivalent of hexadecimal {h}.",
        lambda h: f"If {h} is a hexadecimal number, what is its decimal value?",
        lambda h: f"Turn hex {h} into a base-10 number.",
        lambda h: f"Give me the decimal equivalent of hex {h}.",
        lambda h: f"How much is hexadecimal {h} in decimal?",
        lambda h: f"Calculate what hex {h} equals in base 10.",
        lambda h: f"Interpret {h} as hexadecimal and convert to decimal.",
    ],
}
